Pre-push formatting updates

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -3,42 +3,42 @@ NAME=$(git branch | grep '*' | sed 's/* //')
 
 if [ ! $NAME ]
 then
-  NAME='(empty branch)'
+	NAME='(empty branch)'
 fi
 
 echo "Running pre-push hook on $NAME"
 
-# don't run on rebase
-if [ $NAME != '(no branch)' ]
+# Don't run on rebase
+if [ "$NAME" != "(no branch)" ]
 then
 
-  CHANGES=$(git diff --numstat | wc -l)
-  CACHED_CHANGES=$(git diff --cached --numstat | wc -l)
-  TOTAL_CHANGES=$(($CHANGES + $CACHED_CHANGES))
+	CHANGES=$(git diff --numstat | wc -l)
+	CACHED_CHANGES=$(git diff --cached --numstat | wc -l)
+	TOTAL_CHANGES=$(($CHANGES + $CACHED_CHANGES))
 
-  if [ $TOTAL_CHANGES -ne "0" ]
-  then
-	  echo "Stashing changes..."
-	  git stash save -k -u
-	  echo "Changes stashed"
-  fi
+	if [ $TOTAL_CHANGES -ne "0" ]
+	then
+		echo "Stashing changes..."
+		git stash save -k -u
+		echo "Changes stashed"
+	fi
 
-  npm test
+	npm test
 
-  RETVAL=$?
+	RETVAL=$?
 
-  if [ $TOTAL_CHANGES -ne "0" ]
-  then
-	echo "Restoring stash..."
-	git stash pop -q
-	echo "Stash restored"
-  fi
+	if [ $TOTAL_CHANGES -ne "0" ]
+	then
+		echo "Restoring stash..."
+		git stash pop -q
+		echo "Stash restored"
+	fi
 
-  if [ $RETVAL -ne 0 ]
-  then
-	echo "Pre-push hook failed"
-	exit $RETVAL
-  fi
+	if [ $RETVAL -ne 0 ]
+	then
+		echo "Pre-push hook failed"
+		exit $RETVAL
+	fi
 
-  echo "Pre-push hook succeeded"
+	echo "Pre-push hook succeeded"
 fi
